### ISSUE TITLE
[Bitcoin-Wallet] [V1.0.2]App failed to open

### ISSUE THREAD

**Issue by qbrave1** [hoanghiephui/Bitcoin-Wallet#13]
### Actual behavior
App crashing again and again ,can not open the app.

### Expected behavior
Expected that i can open the app and can use successfully

### How to reproduce:
1.Download the app.
2.Then Open the application
6.Note the Bug.

### Information
* App version:v1.0.2
* OS:Android 6.0.1
* Device:Samsung j7
### Recording of the bug
https://www.youtube.com/watch?v=PRp-9OCknSY

### logcat:
<pre><code>E/AndroidRuntime(31889): FATAL EXCEPTION: main

E/AndroidRuntime(31889): Process: com.bitcoin.wallet.btc, PID: 31889

E/AndroidRuntime(31889): java.lang.VerifyError: Verifier rejected class com.bitcoin.wallet.btc.BitcoinApplication due to bad method void com.bitcoin.wallet.btc.BitcoinApplication.initConfigs() (declaration of 'com.bitcoin.wallet.btc.BitcoinApplication' appears in /data/app/com.bitcoin.wallet.btc-1/base.apk)

E/AndroidRuntime(31889): 	at java.lang.reflect.Constructor.newInstance(Native Method)

E/AndroidRuntime(31889): 	at java.lang.Class.newInstance(Class.java:1690)

E/AndroidRuntime(31889): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1002)

E/AndroidRuntime(31889): 	at android.app.Instrumentation.newApplication(Instrumentation.java:987)

E/AndroidRuntime(31889): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:623)

E/AndroidRuntime(31889): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4966)

E/AndroidRuntime(31889): 	at android.app.ActivityThread.access$1600(ActivityThread.java:177)

E/AndroidRuntime(31889): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493)

E/AndroidRuntime(31889): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime(31889): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(31889): 	at android.app.ActivityThread.main(ActivityThread.java:5912)

E/AndroidRuntime(31889): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(31889): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(31889): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(31889): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)</code></pre>

**Comment by hoanghiephui** [comment]
Thank you for your feedback. Do you download from Google Play or from GitHub?
Please uninstall that version, and the new download from Google Play.

**Comment by qbrave1** [comment]
i am very luck to for your feedback.
@hoanghiephui the new download from google play and same to problem.
 uninstall that version and download new version same problem.
thanks you

**Comment by hoanghiephui** [comment]
@qbrave1 Please download and install from here
[Download](https://github.com/hoanghiephui/Bitcoin-Wallet/blob/master/mobile-orginal-release.apk)
