### ISSUE TITLE
BUG FOUND IN Bitcoin Wallet The application crashes when I click on the request BTC

### ISSUE THREAD

**Issue by XAMIR555** [hoanghiephui/Bitcoin-Wallet#4]

**Comment by XAMIR555** [comment]
> 
> # Project Information
> 
>     * Repository: https://github.com/hoanghiephui/Bitcoin-Wallet
> 
>     * Project Name:  Bitcoin-Wallet
> 
> 
> # Expected behavior
> # Actual behavior
> 
> The application crashes when I click on the request BTC
> # How to reproduce
> 
> 1-Download the app and open it
> 2-
> 3-
> 4-
> 
>     * Browser/App version:
> 
>     * Operating system: 6.0.1
> 
>     * Smartphone: Galaxy j7
> 
> 
> # Recording Of The Bug
> 
> ![20190518_160109](https://user-images.githubusercontent.com/49812927/57968646-10d8bf80-7922-11e9-871c-b090712c1836.gif)
> # My Github Account
> 
> https://github.com/facebook-786
> # Logcat
> 
> ```
> E/AndroidRuntime(10897): FATAL EXCEPTION: main
> 
> E/AndroidRuntime(10897): Process: com.bitcoin.wallet.btc, PID: 10897
> 
> E/AndroidRuntime(10897): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bitcoin.wallet.btc/com.bitcoin.wallet.btc.ui.activitys.RequestCoinActivity}: android.view.InflateException: Binary XML file line #83: Error inflating class TextView
> 
> E/AndroidRuntime(10897): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2695)
> 
> E/AndroidRuntime(10897): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769)
> 
> E/AndroidRuntime(10897): 	at android.app.ActivityThread.access$900(ActivityThread.java:177)
> 
> E/AndroidRuntime(10897): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
> 
> E/AndroidRuntime(10897): 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 
> E/AndroidRuntime(10897): 	at android.os.Looper.loop(Looper.java:135)
> 
> E/AndroidRuntime(10897): 	at android.app.ActivityThread.main(ActivityThread.java:5910)
> 
> E/AndroidRuntime(10897): 	at java.lang.reflect.Method.invoke(Native Method)
> 
> E/AndroidRuntime(10897): 	at java.lang.reflect.Method.invoke(Method.java:372)
> 
> E/AndroidRuntime(10897): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
> 
> E/AndroidRuntime(10897): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
> 
> E/AndroidRuntime(10897): Caused by: android.view.InflateException: Binary XML file line #83: Error inflating class TextView
> 
> E/AndroidRuntime(10897): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
> 
> E/AndroidRuntime(10897): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
> 
> E/AndroidRuntime(10897): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
> 
> E/AndroidRuntime(10897): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
> 
> E/AndroidRuntime(10897): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
> 
> E/AndroidRuntime(10897): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
> 
> E/AndroidRuntime(10897): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
> 
> E/AndroidRuntime(10897): 	at com.bitcoin.wallet.btc.base.BaseActivity.onCreate(BaseActivity.kt:38)
> 
> E/AndroidRuntime(10897): 	at android.app.Activity.performCreate(Activity.java:6178)
> 
> E/AndroidRuntime(10897): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
> 
> E/AndroidRuntime(10897): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2648)
> 
> E/AndroidRuntime(10897): 	... 10 more
> 
> E/AndroidRuntime(10897): Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0800b7
> 
> E/AndroidRuntime(10897): 	at android.content.res.Resources.getResourceName(Resources.java:2413)
> 
> E/AndroidRuntime(10897): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2908)
> 
> E/AndroidRuntime(10897): 	at android.content.res.Resources.loadDrawable(Resources.java:2821)
> 
> E/AndroidRuntime(10897): 	at android.content.res.Resources.loadDrawable(Resources.java:2670)
> 
> E/AndroidRuntime(10897): 	at android.content.res.TypedArray.getDrawable(TypedArray.java:761)
> 
> E/AndroidRuntime(10897): 	at android.widget.TextView.(TextView.java:927)
> 
> E/AndroidRuntime(10897): 	at android.widget.TextView.(TextView.java:685)
> 
> E/AndroidRuntime(10897): 	at androidx.appcompat.widget.AppCompatTextView.(AppCompatTextView.java:87)
> 
> E/AndroidRuntime(10897): 	at androidx.appcompat.widget.AppCompatTextView.(AppCompatTextView.java:83)
> 
> E/AndroidRuntime(10897): 	at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:177)
> 
> E/AndroidRuntime(10897): 	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:102)
> 
> E/AndroidRuntime(10897): 	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
> 
> E/AndroidRuntime(10897): 	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
> 
> E/AndroidRuntime(10897): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
> 
> E/AndroidRuntime(10897): 	... 20 more
> ```
